services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: voter
      POSTGRES_PASSWORD: voter
      POSTGRES_DB: voter
    volumes:
      - voter_pg:/var/lib/postgresql/data

volumes:
  voter_pg:
